<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->renderable(function (ValidationException $exception, $request) {
            if (!$request->wantsJson()) {
                return null; // Laravel handles as usual
            }

            if ($request->expectsJson()) {
                // return response()->json(['status' => 500, 'message' => "There were some Errors", 'errors' => $exception->validator->getMessageBag()->getMessages()]);
                $error_arr = $exception->validator->getMessageBag()->getMessages();

                $statement = '';
                foreach ($error_arr as $key => $e) {
                    // dd($e);
                    $statement .= implode(",", $e);

                    // foreach ($e as $statements) {
                    //     $statement += "," . $e;
                    // }
                }
                // dd($statement);
                // dd($error_arr);
                return response()->json(['status' => 500, 'message' => $statement, 'result' => null]);
            }
            // $exception->validator->getMessageBag()->getMessages()
            // throw CustomerValidationException::withMessages(
            //     $exception->validator->getMessageBag()->getMessages()
            // );
        });
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['status' => 401, 'message' => "Unauthenticated"], 401);
        }

        return parent::render($request, $exception); // TODO: Change theautogenerated stub
    }
}
