<!DOCTYPE html>
<html lang="en" style="-webkit-box-sizing: border-box; box-sizing: border-box; -webkit-text-size-adjust: 100%; line-height: 28px; overflow-x: hidden; overflow-y: auto;background-color: #d9d9d9;">

<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="smb">
    <title>Circle Lotto</title>
    <style>
        /* .hover-btn:hover {
            background: #133F59 !important;
            color: #fff !important;
        }

        .hover-link:hover {
            color: #133F59 !important;
        } */
        /*! Generated by Font Squirrel (https://www.fontsquirrel.com) on March 20, 2024 */



        /* @font-face {
            font-family: 'new_orderbold';
            src: url('assets/fonts/new_order_bold-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_bold-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'new_orderlight';
            src: url('assets/fonts/new_order_light-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_light-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        } */




        @font-face {
            font-family: 'new_ordermedium';
            src: url('assets/fonts/new_order_medium-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_medium-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        /* @font-face {
            font-family: 'new_orderregular';
            src: url('assets/fonts/new_order_regular-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_regular-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'new_ordersemibold';
            src: url('assets/fonts/new_order_semibold-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_semibold-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        } */

        body {
            margin: 0;
            padding: 0;
            background-color: #d9d9d9;
            /* src: url('fonts/New Order Bold.otf'); */
            font-family: Arial, sans-serif;
        }

        table {
            border-spacing: 0;
        }

        td {
            padding: 0;
        }

        img {
            border: 0;
        }

        .wrapper {
            width: 100%;
            table-layout: fixed;
            background-color: #d9d9d9;
            /* padding-bottom: 60px; */
        }

        .main {
            margin: 0 auto;
            width: 100%;
            max-width: 600px;
            height: 100%;
            max-height: 600px;
            border-spacing: 0;
            color: black;
            /*background-color: #E94E1B;*/
        }

        .footer {
            margin: 0 auto;
            width: 100%;
            max-width: 600px;
            height: 100%;
            /* max-height: 600px; */
            border-spacing: 0;
            background-color: #E94E1B;
        }
    </style>
</head>

<body style="line-height: normal; overflow: hidden; background-color: #d9d9d9;">
    <center class="wrapper">
        <table class="main" width="100%" height="100%">
            <!-- asfdasf -->
            <!-- Logo Section Start -->
            <tr>
                <td style="text-align: center;padding-top: 50px;">
                    <img src="{{url('assets/images/circle-lotto-logo')}}" alt="Circle Lotto Logo" title="Circle Lotto Logo" style="height: 50px;width: 50px;">
                </td>
            </tr>
            <!-- Logo Section End -->

            <!-- Header Section Start -->
            <tr>
                <td style="text-align: center;font-weight: 400;font-size: 30px;padding-top: 50px;">
                    Your code is: {{ $code }}
                </td>
            </tr>
            <!-- Header Section End -->

            <!-- Body Section Start -->
            <tr>
                <td style="margin: 0 auto;width: 100%;max-width: 600px;padding: 50px 10px 0 10px;font-size: 18px;line-height: 26px;">
                    This Code will be active for 5mins. If you don't enter it on the Circle Lotto Application you just
                    signed up for within that time, you can resend it by re-registering and filling out the form again.
                </td>
            </tr>

            <tr>
                <td style="margin: 0 auto;width: 100%;max-width: 600px;padding: 25px 10px 0 10px;font-size: 18px;line-height: 26px;">
                    If you don't recognise or expect this email, you can always report suspicious behaviour to our
                    support team.
                </td>
            </tr>

            <tr>
                <td style="margin: 0 auto;width: 100%;max-width: 600px;padding: 25px 10px 25px 10px;font-size: 18px;line-height: 26px;">
                    The Circle Lotto Team
                </td>
            </tr>
            <!-- Body Section End -->

        </table>
        <!-- Footer Sectin Start -->
        <table class="footer" style="padding: 0px;">
            <tr>
                <td style="text-align: center;padding-top: 50px;">
                    <img src="{{url('assets/images/circle-lotto-footer-img-png')}}.png" alt="Circle Lotto Footer Logo" style="width: 200px;">
                </td>
            </tr>
            <tr>
                <td style="text-align: center;color: #27348B;padding: 30px 0 30px 0;line-height: 26px;">
                    Update your email preferences or unsubscribe here <br>
                    © 2021 Circle Lotto <br>
                    UK & Northern Ireland
                </td>
            </tr>
        </table>
        <!-- Footer Section End -->
    </center>
</body>

</html>