<!DOCTYPE html>
<html lang="en" style="-webkit-box-sizing: border-box; box-sizing: border-box; -webkit-text-size-adjust: 100%; line-height: 28px; overflow-x: auto; overflow-y: auto;background-color: #d9d9d9;">

<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="smb">
    <title>Circle Lotto</title>
    <style>
        /* .hover-btn:hover {
            background: #133F59 !important;
            color: #fff !important;
        }

        .hover-link:hover {
            color: #133F59 !important;
        } */
        /*! Generated by Font Squirrel (https://www.fontsquirrel.com) on March 20, 2024 */



        /* @font-face {
            font-family: 'new_orderbold';
            src: url('assets/fonts/new_order_bold-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_bold-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'new_orderlight';
            src: url('assets/fonts/new_order_light-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_light-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        } */




        @font-face {
            font-family: 'new_ordermedium';
            src: url('assets/fonts/new_order_medium-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_medium-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        /* @font-face {
            font-family: 'new_orderregular';
            src: url('assets/fonts/new_order_regular-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_regular-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'new_ordersemibold';
            src: url('assets/fonts/new_order_semibold-webfont.woff2') format('woff2'),
                url('assets/fonts/new_order_semibold-webfont.woff') format('woff');
            font-weight: normal;
            font-style: normal;

        } */

        body {
            margin: 0;
            padding: 0;
            background-color: #d9d9d9;
            /* src: url('fonts/New Order Bold.otf'); */
            font-family: Arial, sans-serif;
        }

        table {
            border-spacing: 0;
        }

        td {
            padding: 0;
        }

        img {
            border: 0;
        }

        .wrapper {
            width: 100%;
            table-layout: fixed;
            background-color: #d9d9d9;
            /* padding-bottom: 60px; */
        }

        .main {
            margin: 0 auto;
            width: 100%;
            max-width: 600px;
            height: 100%;
            max-height: 600px;
            border-spacing: 0;
            color: black;
            /*background-color: #E94E1B;*/
        }

        .footer {
            margin: 0 auto;
            width: 100%;
            max-width: 600px;
            height: 100%;
            /* max-height: 600px; */
            border-spacing: 0;
            background-color: #E94E1B;
        }

        .row {
            display: flex;
            /* text-align: center; */
            flex-wrap: wrap;
            flex-direction: row;
            align-content: center;
            justify-content: center;
            align-items: center;
            padding-top: 25px;
        }

        .row0 {
            display: flex;
            /* text-align: center; */
            flex-wrap: nowrap;
            flex-direction: row;
            /* align-content: center; */
            /* justify-content: center; */
            align-items: flex-start;
            padding-top: 25px;
        }

        .row0 .left {
            line-height: 20px;
        }

        span.circleName {
            color: #27348B;
            font-weight: bold;
        }

        span.circleType {
            color: #27348B;
            font-weight: lighter;
        }

        span.jackpot {
            color: #E94E1B;
            font-weight: bolder;
        }

        .right {
            display: flex;
            flex-direction: row;
            align-content: center;
            justify-content: center;
            align-items: center;
            flex-wrap: nowrap;
            margin-left: 57px
        }

        .rightNumbers {
            padding-left: 50px;
        }

        /* .middle ul {
            border: 2px solid #27348B;
            border-radius: 20px;
            background-color: white;
            display: flex;
            width: 176px;
            flex-direction: row;
            flex-wrap: wrap;
        } */

        .top {
            color: #27348B;
            padding-bottom: 5px;
            font-size: 13px;
            font-weight: 700;
        }

        .middle {
            border: 2px solid #27348B;
            border-radius: 40px;
            background-color: white;
            display: flex;
            /* width: 271px; */
            flex-direction: row;
            flex-wrap: nowrap;
            /* align-items: flex-start; */
        }

        /* .middle ul li {
            margin: 5px;
        } */
        .middle>div {
            margin: 2px;
        }

        .col5 {
            border-radius: 50%;
            width: 15px;
            height: 15px;
            padding: 5px;
            background: #27348B;
            border: 1px solid #27348B;
            color: #fff;
            /* text-align: center; */
            font-size: 14px;
            font-weight: bold;
        }

        .col6 {
            border-radius: 50%;
            width: 15px;
            height: 15px;
            padding: 5px;
            background: #fff;
            border: 1px solid #FFC601;
            color: #27348B;
            /* text-align: center; */
            font-size: 14px;
            font-weight: bolder;
        }

        /* .col3 {
            border: 1px solid #27348B;
            border-radius: 50%;
        } */

        .right>div {
            margin: 5px;
        }
    </style>
</head>

<body style="line-height: normal; overflow: auto; background-color: #d9d9d9;">
    <center class="wrapper">
        <table class="main" width="100%" height="100%">
            <!-- asfdasf -->
            <!-- Logo Section Start -->
            <tr>
                <td style="text-align: center;padding:5px 0 5px 0;background-color: #E94E1B;">
                    <img src="{{url('assets/images/circle-lotto-footer-img-png')}}.png" alt="Circle Lotto Logo" title="Circle Lotto Logo" style="height: 50px;width: 100px;">
                </td>
            </tr>
            <!-- Logo Section End -->


            <!-- Header Section Start -->
            @if($winner != '1')
            <tr>
                <td style="text-align: center;">
                    <!-- <img src="{{url('assets/images/circle-lotto-banner.png')}}" alt="Circle Lotto Footer Logo" style="width: 600px;height:auto"> -->
                    <img src="{{url('assets/images/circle-lotto-banner.png')}}" alt="Circle Lotto Footer Logo" style="width: 100%;height:100%;">
                </td>
            </tr>
            @else
            <tr>
                <td style="text-align: center;">
                    <!-- <img src="{{url('assets/images/circle-lotto-banner-winner.png')}}" alt="Circle Lotto Footer Logo" style="width: 600px;height:auto"> -->
                    <img src="{{url('assets/images/circle-lotto-banner-winner.png')}}" alt="Circle Lotto Footer Logo" style="width: 100%;height:100%;">
                </td>
            </tr>
            @endif
            <!-- Header Section End -->

            <tr>
                <td style="padding-left: 49px;" class="row0">
                    <div class="left">
                        <p>
                            <span class="circleName">{{$circle_name}}</span> <br>
                            <span class="circleType">{{$circle_type == '1' ? 'Private Circle' : 'Public Circle'}}</span> <br>
                            <span class="jackpot">Jackpot £{{$total_circle_amount}}</span>
                        </p>
                    </div>
                    <div class="rightNumbers" style="text-align: center;">
                        <div class="top">
                            Draw Results
                        </div>
                        <div class="middle">
                            <div class="col5">
                                {{$ticket[0]}}
                            </div>
                            <div class="col5">
                                {{$ticket[1]}}
                            </div>
                            <div class="col5">
                                {{$ticket[2]}}
                            </div>
                            <div class="col5">
                                {{$ticket[3]}}
                            </div>
                            <div class="col5">
                                {{$ticket[4]}}
                            </div>
                            <div class="col6">
                                {{$ticket[5]}}
                            </div>
                            <div class="col6">
                                {{$ticket[6]}}
                            </div>
                            <!-- <ul style="list-style-type: none;padding:0;margin:0;">
                                <li>6</li>
                                <li>9</li>
                                <li>12</li>
                                <li>17</li>
                                <li>21</li>
                                <li>10</li>
                                <li>11</li>
                            </ul> -->
                        </div>
                        @if($winner != '1')
                        <div class=" footerNum" style="text-align: center;text-align: center;color: rgb(0, 0, 0, 0.5);padding: 10px 0 15px 0;">
                            Sorry you didn't win this time.
                        </div>
                        @else
                        <div class=" footerNum" style="text-align: center;text-align: center;color: #E94E1B;padding: 10px 0 15px 0;font-weight:700;">
                            YOU WIN THE JACKPOT !!!
                        </div>
                        @endif
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <hr style="border: 0.59px solid rgb(233, 78, 27,0.3);width:500px;">
                </td>
            </tr>

            <tr>
                <td style="text-align: center;color:#27348B;font-size: 18px;font-weight: 500;">
                    <p>Check out who won, in your circle,<br> download the full results table</p>
                </td>
            </tr>

            <tr>
                <td style="text-align: center;padding-top:15px">
                    <a href="" class="button" style="background-color:#E94E1B;color: #fff;border: 3.45px solid RGB(39,52,139,0.4);padding: 10px 35px;border-radius: 10px;font-weight:bold;font-size:16px;text-decoration:none">
                        DOWNLOAD NOW
                    </a>
                </td>
            </tr>

            <tr>
                <td style="padding-top:30px;">
                    <hr style="border: 0.59px solid rgb(233, 78, 27,0.3);width:500px;">
                </td>
            </tr>

            <tr>
                <!-- <td class="row"> -->
                <td>
                    <div class="row" style="display: flex;flex-wrap: wrap;flex-direction: row;align-content: center;justify-content: center;align-items: center;padding-top: 25px;">
                        <div class="left">
                            <a href="{{url('/')}}" style="color:#27348B;font-size:17px;font-weight:500;text-decoration: none;">circlelotto.com</a>
                        </div>
                        <div class="right">
                            <div class="col1">
                                <a href=""><img src="{{url('assets/images/facebook-icon.png')}}" style="width: 30px;height:auto" alt="Facebook"></a>
                            </div>
                            <div class="col2">
                                <a href=""><img src="{{url('assets/images/instagram-icon.png')}}" style="width: 30px;height:auto" alt="Instagram"></a>
                            </div>
                            <div class="col3">
                                <a href=""><img src="{{url('assets/images/x-icon.png')}}" style="width: 30px;height:auto" alt="X"></a>
                            </div>
                            <div class="col4">
                                <a href=""><img src="{{url('assets/images/whatsapp-icon.png')}}" style="width: 30px;height:auto" alt="Whats App"></a>
                            </div>
                        </div>
                    </div>
                </td>
                <!-- </td> -->
            </tr>

            <tr>
                <td style="text-align: center;color: #6D6D6D;padding: 20px 0 30px 0;line-height: 22px;font-size: 14px;">
                    Update your email preferences or unsubscribe here <br>
                    © 2021 Circle Lotto <br>
                    UK & Northern Ireland
                </td>
            </tr>
        </table>
        <!-- Footer Sectin Start -->
        <!-- <table class="footer" style="padding: 0px;">
            <tr>
                <td style="text-align: center;padding-top: 50px;">
                    <img src="{{url('assets/images/circle-lotto-footer-img-png')}}.png" alt="Circle Lotto Footer Logo" style="width: 200px;">
                </td>
            </tr>
            <tr>
                <td style="text-align: center;color: #27348B;padding: 30px 0 30px 0;line-height: 26px;">
                    Update your email preferences or unsubscribe here <br>
                    © 2021 Circle Lotto <br>
                    UK & Northern Ireland
                </td>
            </tr>
        </table> -->
        <!-- Footer Section End -->
    </center>
</body>

</html>